Feature/UI/postinfo
swent-group10/polyfit pull request #181
Opened 2024-04-28 15:43 UTC by antomax33

2024-04-28 17:01 UTC, RandomUsername1315 requested changes
Looks really good and the modularity is awesome! It could be a good idea to refactor some of these functions into their own files within the components folder. This would make reusing them easier in the future. 

A few minor issues, but there's just one that really needs fixing: the displaying all the ingredients of a meal instead of only a selected few.

2024-04-28 17:27 UTC, antomax33 commented on app/src/main/java/com/github/se/polyfit/ui/screen/PostInfoScreen.kt
> +*/
They are the 2 previews, one when no post is near and one with differents posts.

2024-04-28 17:59 UTC, antomax33 commented on app/src/main/java/com/github/se/polyfit/ui/screen/PostInfoScreen.kt
> +package com.github.se.polyfit.ui.screen
When called from MainActivity or somewhere else, we can call GenericScreen with postInfo as argument.

2024-04-28 18:23 UTC, RandomUsername1315 commented on app/src/main/java/com/github/se/polyfit/ui/screen/PostInfoScreen.kt
> +*/
Ok I see !

2024-04-28 18:30 UTC, RandomUsername1315 commented on app/src/main/java/com/github/se/polyfit/ui/screen/PostInfoScreen.kt
> +package com.github.se.polyfit.ui.screen
Ok I understand. I wasn't sure because I could not see it anywhere.

2024-04-29 22:42 UTC, sharif-bbd commented on app/src/main/java/com/github/se/polyfit/ui/screen/PostInfoScreen.kt
> +*/
if they intend to stay commented you might as well take them off or move them to somewhere else.

2024-04-29 23:26 UTC, sharif-bbd reviewed
Overall really good implementation, all the changes are pretty small and consist mainly of consistency around the use of the material theme for color, shapes and text style

2024-04-29 23:26 UTC, sharif-bbd commented on app/src/main/java/com/github/se/polyfit/ui/screen/PostInfoScreen.kt
> +          .width(330.dp)
This is redundant as you set the width twice. You would use WidthIn to set a range.

2024-04-30 08:24 UTC, medwardson commented on app/src/main/java/com/github/se/polyfit/ui/screen/PostInfoScreen.kt
> +*/
I think it is ok to leave them, it helps anyone who is working on the file quickly get an understanding of it. There's not really anywhere else to move it, as the Preview belongs at the bottom of the file

2024-04-30 11:41 UTC, RandomUsername1315 approved these changes
Awesome job ! The new screen looks amazing !

2024-04-30 11:41 UTC, merged

2024-04-30 11:45 UTC, sharif-bbd approved these changes
Great Job !  Try to prioritize the use of the MaterialTheme when possible.

2024-04-30 11:45 UTC, sharif-bbd commented on app/src/main/java/com/github/se/polyfit/ui/components/postinfo/Card.kt
> +      Modifier.fillMaxWidth().padding(8.dp).shadow(8.dp, shape = CardDefaults.shape)
Try to lean on using MaterialTheme.shapes for the shapes of your components